name: kalender
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2

  # Database & Local Storage
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2

  # UI & Utils
  intl: ^0.19.0
  table_calendar: ^3.1.0
  equatable: ^2.0.5
  flutter_local_notifications: ^17.0.0
  
  # Tambahkan dependensi timezone
  timezone: ^0.9.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true